### PR TITLE
Fix lint errors

### PR DESCRIPTION
**Pull request by martin-g**
This PR is based on top of https://github.com/conda-forge/perl-scalar-list-utils-feedstock/pull/1 but also fixes a lint error (about stdlib(c))

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please ping team

**Comment by martin-g** [comment]
@conda-forge/core Could someone please help with the review and merge of this PR ? Thank you!

**Comment by wolfv** [comment]
Thanks!

**Pull request merged**
